### ISSUE TITLE
The batch script can't find winrar in any other folder

### ISSUE THREAD

**Issue by Dantoza** [NaeemBolchhi/WinRAR-Activator#1]
I installed winrar with scoop, and the script doesn`t recognize the programme is installed

**Comment by NaeemBolchhi** [comment]
Let me know where WinRAR is installed on your system and I'll update the script to check that directory as well.

Meanwhile,
Download and place this file in your installation location.
https://github.com/NaeemBolchhi/WinRAR-Activator/blob/main/rarreg.key
Make sure the filename remains `rarreg.key`.

**Comment by Dantoza** [comment]
WinRAR is installed here:
C:\Users\ %USERNAME% \scoop\apps\winrar\current\WinRAR.exe
Hope that helps!

**Comment by NaeemBolchhi** [comment]
Fixed with [86d8bd9](https://github.com/NaeemBolchhi/WinRAR-Activator/commit/86d8bd92696ab77dcaced004d03f07b8e61ea9cb).
